fields:
  - name: id
    type: string
    required: true
    unique: true
  - name: titulo
    type: string
    required: true
  - name: fecha
    type: date
    format: "YYYY-MM-DD"
    required: false
  - name: url
    type: string
    required: true
    unique: true
  - name: fuente
    type: string
    required: true
  - name: autor
    type: string
    required: false
  - name: capturado_ts
    type: datetime
    format: "YYYY-MM-DDTHH:MM:SSZ"
    required: true
